### PR TITLE
Updating to newer version of PHP

### PR DESCRIPTION
**Pull request by serroba**
Hey @petrkotek 

I think you would get the idea quite easily on what's going here :D

Could you please accept this PR?

Thanks in advance man!

Hope things are going well ;)

### CODE REVIEW

**Comment by petrkotek** [comment]
Looks like something in https://github.com/FriendsOfPHP/PHP-CS-Fixer changed. Feel free to comment out `  - ./phpcs.sh --dry-run --diff` in the `.travis.yml` for now if you don't want to bother with that at the moment or wait for me to fix that :)

**Comment by serroba** [comment]
Thanks @petrkotek !!!

**Comment by petrkotek** [comment]
no worries, thank you for the contribution! 🥇

**Comment by petrkotek** [comment]
Note that I've tagged it with version `v2.0.0` because of the dropped support of PHP 7.0.

Let me know if any concerns!

**Comment by serroba** [comment]
Thanks @petrkotek 

I hope things are going very well!

**Pull request merged**
